SELECT P.ID_PESSOA 
		,CON.ID_PESSOA
FROM PESSOA  P
	RIGHT OUTER JOIN CONTATO CON
	ON P.ID_PESSOA = CON.ID_PESSOA;
	
SELECT P.ID_PESSOA 
		,P.NOME 
		,pxpe.ID_PESSOA
       ,pxpe.ID_ENDERECO
       ,ep.ID_ENDERECO 
       ,ep.LOGRADOURO 
FROM PESSOA P
	RIGHT OUTER JOIN PESSOA_X_PESSOA_ENDERECO pxpe ON (pxpe.ID_PESSOA = P.ID_PESSOA) 
	RIGHT OUTER JOIN ENDERECO_PESSOA ep ON (ep.ID_ENDERECO = pxpe.ID_ENDERECO)

SELECT P.ID_PESSOA 
		,P.NOME 
		,pxpe.ID_PESSOA
       ,pxpe.ID_ENDERECO
       ,ep.ID_ENDERECO 
       ,ep.LOGRADOURO
       ,CON.ID_PESSOA
FROM PESSOA P
	RIGHT OUTER JOIN PESSOA_X_PESSOA_ENDERECO pxpe ON (pxpe.ID_PESSOA = P.ID_PESSOA) 
	RIGHT OUTER JOIN ENDERECO_PESSOA ep ON (ep.ID_ENDERECO = pxpe.ID_ENDERECO)
	RIGHT OUTER JOIN CONTATO CON ON (CON.ID_PESSOA = pxpe.ID_PESSOA)

SELECT P.ID_PESSOA 
		,CON.ID_PESSOA
FROM PESSOA  P
	FULL OUTER JOIN CONTATO CON
	ON P.ID_PESSOA = CON.ID_PESSOA
	
SELECT P.ID_PESSOA 
		,P.NOME 
		,pxpe.ID_PESSOA
       ,pxpe.ID_ENDERECO
       ,ep.ID_ENDERECO 
       ,ep.LOGRADOURO 
FROM PESSOA P
	FULL OUTER JOIN PESSOA_X_PESSOA_ENDERECO pxpe ON (pxpe.ID_PESSOA = P.ID_PESSOA) 
	FULL OUTER JOIN ENDERECO_PESSOA ep ON (ep.ID_ENDERECO = pxpe.ID_ENDERECO)
	
SELECT P.ID_PESSOA 
		,P.NOME 
		,pxpe.ID_PESSOA
       ,pxpe.ID_ENDERECO
       ,ep.ID_ENDERECO 
       ,ep.LOGRADOURO
       ,CON.ID_PESSOA
FROM PESSOA P
	FULL OUTER JOIN PESSOA_X_PESSOA_ENDERECO pxpe ON (pxpe.ID_PESSOA = P.ID_PESSOA) 
	FULL OUTER JOIN ENDERECO_PESSOA ep ON (ep.ID_ENDERECO = pxpe.ID_ENDERECO)
	FULL OUTER JOIN CONTATO CON ON (CON.ID_PESSOA = pxpe.ID_PESSOA)

SELECT P.NOME
FROM PESSOA P 
WHERE EXISTS (SELECT pxpe.ID_PESSOA
			FROM PESSOA_X_PESSOA_ENDERECO pxpe
			WHERE pxpe.ID_PESSOA = P.ID_PESSOA)
			
SELECT P.ID_PESSOA ,
		P.NOME
FROM PESSOA P
UNION 
SELECT ep.ID_ENDERECO , 
		ep.LOGRADOURO
FROM ENDERECO_PESSOA ep
