/*CREATE TABLE VEM_SER.PAIS (
	ID_PAIS NUMBER(38) PRIMARY KEY NOT NULL,
	NOME VARCHAR2(50) UNIQUE NOT NULL
);
 * 
 
CREATE TABLE VEM_SER.ESTADO (
	ID_ESTADO NUMBER(38) PRIMARY KEY NOT NULL,
	ID_PAIS NUMBER(38) NOT NULL,
	NOME VARCHAR2(50) UNIQUE NOT NULL
);

CREATE TABLE VEM_SER.CIDADE (
	ID_CIDADE NUMBER(38) NOT NULL,
	ID_ESTADO NUMBER(38) NOT NULL,
	ID_PAIS NUMBER(38) NOT NULL,
	NOME VARCHAR2(50) UNIQUE NOT NULL,
	CONSTRAINT PK_CIDADE PRIMARY KEY (ID_CIDADE, ID_ESTADO),
	CONSTRAINT FK_CIDADE_ESTADO FOREIGN KEY (ID_ESTADO) REFERENCES ESTADO(ID_ESTADO)
);

CREATE TABLE VEM_SER.BAIRRO (
	ID_CIDADE NUMBER(38) NOT NULL,
	ID_ESTADO NUMBER(38) NOT NULL,
	ID_BAIRRO NUMBER(38) NOT NULL,
	NOME VARCHAR2(50) UNIQUE NOT NULL,
	CONSTRAINT PK_BAIRRO PRIMARY KEY (ID_CIDADE, ID_BAIRRO),
	CONSTRAINT FK_BAIRRO_CIDADE FOREIGN KEY (ID_CIDADE , ID_ESTADO) REFERENCES CIDADE(ID_CIDADE , ID_ESTADO),
	CONSTRAINT FK_BAIRRO_ESTADO FOREIGN KEY (ID_ESTADO) REFERENCES ESTADO(ID_ESTADO)
);

CREATE TABLE VEM_SER.ENDERECO (
	ID_CIDADE NUMBER(38) NOT NULL,
	ID_ENDERECO NUMBER(38) PRIMARY KEY NOT NULL,
	ID_BAIRRO NUMBER(38) NOT NULL,
	LOGRADOURO VARCHAR2(255) NOT NULL,
	NUMERO NUMBER(38) NOT NULL,
	COMPLEMENTO VARCHAR2(100),
	CEP CHAR(9),
	CONSTRAINT FK_ENDERECO_BAIRRO FOREIGN KEY (ID_BAIRRO, ID_CIDADE) REFERENCES BAIRRO (ID_BAIRRO, ID_CIDADE)
);

CREATE SEQUENCE VEM_SER.SEQ_PAIS
START WITH 1
INCREMENT BY 1
NOCACHE NOCYCLE;

CREATE SEQUENCE VEM_SER.SEQ_ESTADO
START WITH 10
INCREMENT BY 1
NOCACHE NOCYCLE;

CREATE SEQUENCE VEM_SER.SEQ_CIDADE
START WITH 100
INCREMENT BY 1
NOCACHE NOCYCLE;

CREATE SEQUENCE VEM_SER.SEQ_BAIRRO
START WITH 1000
INCREMENT BY 1
NOCACHE NOCYCLE;

CREATE SEQUENCE VEM_SER.SEQ_ENDERECO
START WITH 1000
INCREMENT BY 1
NOCACHE NOCYCLE;

INSERT INTO VEM_SER.PAIS (ID_PAIS, NOME)
VALUES (SEQ_PAIS.nextval , 'São Tomé e Príncipe');
INSERT INTO VEM_SER.PAIS (ID_PAIS, NOME)
VALUES (SEQ_PAIS.nextval , 'Tchéquia República Tcheca');

SELECT * FROM VEM_SER.PAIS;

INSERT INTO VEM_SER.ESTADO (ID_PAIS, NOME, ID_ESTADO)
VALUES (SEQ_PAIS.nextval, 'Água Grande', SEQ_ESTADO.nextval);
INSERT INTO VEM_SER.ESTADO (ID_PAIS, NOME, ID_ESTADO)
VALUES (SEQ_PAIS.nextval, 'Praga', SEQ_ESTADO.nextval);

SELECT * FROM VEM_SER.ESTADO;

INSERT INTO VEM_SER.CIDADE (ID_CIDADE , NOME , ID_ESTADO , ID_PAIS)
VALUES (SEQ_CIDADE.nextval, 'São Tomé', 10 , 6);
INSERT INTO VEM_SER.CIDADE (ID_CIDADE, NOME, ID_ESTADO, ID_PAIS)
VALUES (SEQ_CIDADE.nextval, 'Brun', 11,7);

SELECT * FROM VEM_SER.CIDADE;

INSERT INTO VEM_SER.BAIRRO (ID_CIDADE, NOME, ID_ESTADO, ID_BAIRRO)
VALUES (111, 'Estrada da Benedita Sarvanini do Prado', 10,SEQ_BAIRRO.nextval);
INSERT INTO VEM_SER.BAIRRO (ID_CIDADE, NOME, ID_ESTADO, ID_BAIRRO)
VALUES (112, 'Praça Salvador Pinho', 11,SEQ_BAIRRO.nextval);

SELECT * FROM VEM_SER.BAIRRO;

INSERT INTO VEM_SER.ENDERECO (ID_CIDADE, NUMERO , ID_ENDERECO, ID_BAIRRO, CEP, LOGRADOURO)
VALUES (111, 50, SEQ_ENDERECO.nextval ,1000 ,'13073-290', 'SITIO');
INSERT INTO VEM_SER.ENDERECO (ID_CIDADE, NUMERO, ID_ENDERECO, ID_BAIRRO, CEP, LOGRADOURO)
VALUES (112, 25, SEQ_ENDERECO.nextval, 1001, '13083-875', 'RUA');

SELECT * 
FROM VEM_SER.PAIS 
ORDER BY NOME DESC;

SELECT LOGRADOURO , CEP 
FROM VEM_SER.ENDERECO 
WHERE UPPER(LOGRADOURO) LIKE 'A%';

SELECT *
  FROM ENDERECO 
 WHERE TRIM(CEP) LIKE '%0';

SELECT * 
  FROM ENDERECO 
 WHERE NUMERO BETWEEN 1 AND 100 ;

SELECT *
  FROM ENDERECO 
 WHERE UPPER(LOGRADOURO) LIKE 'RUA%'
ORDER BY CEP DESC ;

SELECT COUNT(ID_ENDERECO) AS QUANTIDADE FROM VEM_SER.ENDERECO 

SELECT COUNT(ID_ENDERECO) 
FROM VEM_SER.ENDERECO 
GROUP BY ID_CIDADE;



UPDATE VEM_SER.ENDERECO 
SET LOGRADOURO = 'Rua Mutamba', COMPLEMENTO = 'Proximo a igreja'
WHERE ID_ENDERECO = 1000;

UPDATE VEM_SER.ENDERECO 
SET LOGRADOURO = 'Rua Estrada Grande', COMPLEMENTO = 'Proximo ao mercado'
WHERE ID_ENDERECO = 1001;

UPDATE VEM_SER.ENDERECO 
SET NUMERO  = 9999999
WHERE ID_ENDERECO = 1001;

SELECT *
FROM VEM_SER.ENDERECO

DELETE
FROM VEM_SER.ENDERECO 
WHERE ID_CIDADE = 
(SELECT MAX (ID_ENDERECO)
FROM ENDERECO);

DELETE
FROM VEM_SER.ENDERECO 
WHERE NUMERO = 9999999;

DELETE
FROM VEM_SER.ENDERECO 
WHERE ID_ENDERECO = 1000;
*/